baseURL = 'https://blog-ami.pages.dev/'
languageCode = "ja-JP"

title = 'タイトルはそのうち考える'
theme = "mainroad"

hasCJKLanguage = true # 日本語・中国語・韓国語の単語カウントを有効にする
summaryLength = 120 # サマリーの長さを120単語にする

[pagination]
pagerSize = 10 # ページ当たりの投稿数

[taxonomies]
  author = "authors" 
  category = "categories"
  tag = "tags"

[Params]
description = "ksera's Personal blog" # サイトの説明
copyright = "ksera" # フッターの著作権表示
opengraph = true # OpenGraphを有効にする
schema = true # Schemaを有効にする
twitter_cards = true # Twitter Cardsを有効にする
readmore = true # 一覧ページでRead moreボタンを表示するか
authorbox = false # 投稿の最後に作者情報を表示するか
toc = true # 目次を表示するか
pager = true # ページャーナビゲーション(前/次のリンク)を表示するか
post_meta = ["author", "date", "categories", "translations"] # 投稿メタ情報の表示順序
mainSections = ["post", "blog", "news"] # ホームページと最近の投稿ウィジェットでセクションを指定
dateformat = "2006-01-02" # 日付のフォーマット
mathjax = true # MathJaxを有効にする
mathjaxPath = "https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.6/MathJax.js" # MathJaxのパス
mathjaxConfig = "TeX-AMS-MML_HTMLorMML" # MathJaxの設定
googleFontsLink = "https://fonts.googleapis.com/css?family=Open+Sans:400,400i,700" # Google Fontsのリンク


[Params.logo]
title = "タイトルはそのうち考える" # ロゴタイトル
[Params.thumbnail]
visibility = ["list", "post"] # サムネイル表示場所
[Params.sidebar]
home = "right" # ホームページのサイドバー位置
list = "left" # 一覧ページのサイドバー位置
single = false # 個別ページでサイドバーを表示するか
widgets = ["search", "archives", "categories", "taglist", "social"] # サイドバーウィジェットの順序
[Params.widgets]
recent_num = 5 # 最近の投稿ウィジェットの投稿数
categories_counter = false # カテゴリウィジェットでカウンターを表示するか
tags_counter = false # タグウィジェットでカウンターを表示するか


[Params.widgets.social]
  cached = false # activate cache if true
  github = "ksera524"


[Params.Author]
  name = "ksera" # 作者名
  bio = "ksera's Japanese software engineer" # 作者の自己紹介
  avatar = "img/img.jpg" # 作者のアバター画像